INSERT INTO stock VALUES ('PETR3');
INSERT INTO stock VALUES ('PETR4');

INSERT INTO quote VALUES ('PETR3', '2.3');
INSERT INTO quote VALUES ('PETR3', '6.1');
INSERT INTO quote VALUES ('PETR3', '9.6');
INSERT INTO quote VALUES ('PETR4', '15.5');
INSERT INTO quote VALUES ('PETR4', '15.1');
INSERT INTO quote VALUES ('PETR4', '10.5');
INSERT INTO quote VALUES ('PETR4', '18.6');
INSERT INTO quote VALUES ('PETR4', '9.6');
